[[main]]
  name = "Engenharia"
  pageRef = "engineering"
  weight = 10

[[main]]
  name = "Kung Fu"
  pageRef = "kung-fu"
  weight = 20

[[main]]
  name = "Filosofia"
  pageRef = "philosophy"
  weight = 30

[[main]]
  name = "Tech Leadership"
  pageRef = "tech-leadership"
  weight = 40

[[main]]
  name = "Podcast"
  pageRef = "podcast"
  weight = 50

[[main]]
  name = "Mentoria"
  pageRef = "mentoring"
  weight = 60

