colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = false
disableTextInHeader = true

[homepage]
  layout = "custom"
  showRecent = false

[article]
  showDate = false
  showReadingTime = false
  showBreadcrumbs = true

[list]
  showBreadcrumbs = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
