colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
disableTextInHeader = false

[homepage]
  layout = "profile"
  showRecent = false

[article]
  showDate = false
  showReadingTime = false
  showBreadcrumbs = true

[list]
  showBreadcrumbs = true

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
